version: 2

jobs:
  swift3-macos:
    macos:
      xcode: "8.3"
    steps:
      - run: brew install vapor/tap/vapor
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  swift4-macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install vapor/tap/vapor
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  swift3-linux:
    docker:
      - image: swift:3.1
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  swift4-linux:
    docker:
      - image: swift:4.0
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - swift3-macos
      - swift4-macos
      - swift3-linux
      - swift4-linux
