version: 2

jobs:
  swift-3:
    docker:
      - image: swift:3.1
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  swift-4:
    docker:
      - image: swift:4.0
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - swift-3
      - swift-4
